# Generated by Django 2.2.7 on 2020-01-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='salt',
            field=models.CharField(default='NBSWY3DPO5XXE3DE', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='key',
            field=models.CharField(max_length=10),
        ),
    ]
